databaseChangeLog:
  - changeSet:
      id: 3.2.0
      author: GraviteeSource Team
      changes:
        - renameColumn:
            newColumnName: organization_id
            oldColumnName: reference_id
            columnDataType: nvarchar(64)
            tableName: identity_providers
        - dropColumn:
            columnName: reference_type
            tableName: identity_providers

        - renameColumn:
            newColumnName: organization_id
            oldColumnName: reference_id
            columnDataType: nvarchar(64)
            tableName: users
        - dropColumn:
            columnName: reference_type
            tableName: users

        - sql:
            - sql: update audits set reference_type = 'ORGANIZATION' where reference_type = 'PORTAL' and (event like 'IDENTITY_PROVIDER%' or event like 'ROLE%' or event like 'USER%' or (event like 'MEMBERSHIP%' and patch like '%organization%'));
        - sql:
            - sql: update audits set reference_type = 'ENVIRONMENT' where reference_type = 'PORTAL';
